In [2]:
import math
import numpy as np
import torch
from PIL import Image
import matplotlib.pyplot as plt
import scipy.io

In [4]:
GT = scipy.io.loadmat("HSI/Urban_gt.mat")
A = np.transpose(GT['A'].reshape(4, 307, 307), (2, 1, 0))
A

array([[[8.08743430e-01, 9.76155164e-02, 0.00000000e+00, 9.36410538e-02],
        [7.81248740e-01, 6.49380650e-02, 0.00000000e+00, 1.53813195e-01],
        [8.02563919e-01, 4.82463693e-02, 0.00000000e+00, 1.49189712e-01],
        ...,
        [0.00000000e+00, 7.36039036e-01, 2.56364155e-01, 7.59680851e-03],
        [1.50678392e-01, 6.46855300e-01, 1.93630235e-01, 8.83607389e-03],
        [1.69004554e-01, 6.47943842e-01, 1.23413859e-01, 5.96377446e-02]],

       [[7.47907311e-01, 1.45588548e-01, 0.00000000e+00, 1.06504141e-01],
        [7.54779597e-01, 8.45191030e-02, 0.00000000e+00, 1.60701300e-01],
        [7.83242012e-01, 6.47067431e-02, 0.00000000e+00, 1.52051245e-01],
        ...,
        [1.72413963e-01, 6.23812097e-01, 2.03773940e-01, 0.00000000e+00],
        [3.70362756e-01, 5.11737432e-01, 1.17899812e-01, 0.00000000e+00],
        [3.75128275e-01, 5.54376442e-01, 1.27923509e-02, 5.77029324e-02]],

       [[7.32288918e-01, 1.58333653e-01, 0.00000000e+00, 1.09377429e-01],
        

In [5]:
np.max(A)

1.0000000000000007

In [6]:
np.min(A)

0.0

In [10]:
E = np.transpose(GT['M'])
E

array([[0.34035088, 0.34965035, 0.36236934, 0.35714286, 0.103     ,
        0.1       , 0.105     , 0.106     , 0.105     , 0.106     ,
        0.106     , 0.108     , 0.104     , 0.106     , 0.107     ,
        0.105     , 0.105     , 0.106     , 0.108     , 0.107     ,
        0.106     , 0.109     , 0.109     , 0.108     , 0.11      ,
        0.111     , 0.111     , 0.112     , 0.113     , 0.112     ,
        0.113     , 0.115     , 0.116     , 0.115     , 0.117     ,
        0.119     , 0.119     , 0.119     , 0.12      , 0.121     ,
        0.123     , 0.124     , 0.124     , 0.122     , 0.126     ,
        0.124     , 0.124     , 0.126     , 0.127     , 0.126     ,
        0.126     , 0.127     , 0.125     , 0.124     , 0.128     ,
        0.131     , 0.124     , 0.133     , 0.132     , 0.13      ,
        0.132     , 0.131     , 0.131     , 0.134     , 0.136     ,
        0.136     , 0.138     , 0.136     , 0.134     , 0.138     ,
        0.137     , 0.134     , 0.139     , 0.14

In [8]:
np.max(GT['M'] @ GT['A'])

0.32700000000000023

In [11]:
for i in range(4):
    E[i,:] = E[i,:] / (np.max(E[i,:]))
E

array([[0.93923752, 0.96490048, 1.        , 0.98557692, 0.28424038,
        0.27596154, 0.28975962, 0.29251923, 0.28975962, 0.29251923,
        0.29251923, 0.29803846, 0.287     , 0.29251923, 0.29527885,
        0.28975962, 0.28975962, 0.29251923, 0.29803846, 0.29527885,
        0.29251923, 0.30079808, 0.30079808, 0.29803846, 0.30355769,
        0.30631731, 0.30631731, 0.30907692, 0.31183654, 0.30907692,
        0.31183654, 0.31735577, 0.32011538, 0.31735577, 0.322875  ,
        0.32839423, 0.32839423, 0.32839423, 0.33115385, 0.33391346,
        0.33943269, 0.34219231, 0.34219231, 0.33667308, 0.34771154,
        0.34219231, 0.34219231, 0.34771154, 0.35047115, 0.34771154,
        0.34771154, 0.35047115, 0.34495192, 0.34219231, 0.35323077,
        0.36150962, 0.34219231, 0.36702885, 0.36426923, 0.35875   ,
        0.36426923, 0.36150962, 0.36150962, 0.36978846, 0.37530769,
        0.37530769, 0.38082692, 0.37530769, 0.36978846, 0.38082692,
        0.37806731, 0.36978846, 0.38358654, 0.39

In [12]:
np.max(np.transpose(E) @ GT['A'])

1.0000000000000007

In [13]:
I = scipy.io.loadmat("HSI/Urban_R162.mat")['Y']
I.shape

(162, 94249)

In [14]:
I = I.astype(float)
for i in range(162):
    I[i,:] = I[i,:] / (np.max(I[i,:]) - np.min(I[i,:]))
I

array([[0.14342105, 0.15263158, 0.15657895, ..., 0.02105263, 0.01578947,
        0.01184211],
       [0.14524422, 0.1529563 , 0.1529563 , ..., 0.02442159, 0.02056555,
        0.01670951],
       [0.15206186, 0.16752577, 0.16365979, ..., 0.03608247, 0.03221649,
        0.02963918],
       ...,
       [0.259     , 0.266     , 0.289     , ..., 0.077     , 0.062     ,
        0.047     ],
       [0.237     , 0.256     , 0.275     , ..., 0.076     , 0.066     ,
        0.057     ],
       [0.264     , 0.307     , 0.275     , ..., 0.061     , 0.05      ,
        0.072     ]])

In [15]:
np.max(GT['M'] @ GT['A'] - I)

0.9763157894736842

In [16]:
np.max(np.transpose(E) @ GT['A'] - I)

0.9763157894736842

In [17]:
I

array([[0.14342105, 0.15263158, 0.15657895, ..., 0.02105263, 0.01578947,
        0.01184211],
       [0.14524422, 0.1529563 , 0.1529563 , ..., 0.02442159, 0.02056555,
        0.01670951],
       [0.15206186, 0.16752577, 0.16365979, ..., 0.03608247, 0.03221649,
        0.02963918],
       ...,
       [0.259     , 0.266     , 0.289     , ..., 0.077     , 0.062     ,
        0.047     ],
       [0.237     , 0.256     , 0.275     , ..., 0.076     , 0.066     ,
        0.057     ],
       [0.264     , 0.307     , 0.275     , ..., 0.061     , 0.05      ,
        0.072     ]])